"""Read-only queries over a .net.xml (NetworkMCP's contract; sumolib adapter)."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Protocol


class NetworkQuery(Protocol):
    def has_edge(self, edge_id: str) -> bool: ...
    def has_lane(self, edge_id: str, lane_index: int) -> bool: ...
    def has_tls(self, tls_id: str) -> bool: ...
    def get_edge(self, edge_id: str) -> Mapping[str, Any]: ...
    def get_lanes(self, edge_id: str) -> Sequence[Mapping[str, Any]]: ...
    def get_neighbours(self, edge_id: str) -> Sequence[str]: ...
    def shortest_path(self, from_edge: str, to_edge: str) -> Sequence[str]: ...
    def edges_in_bbox(self, bbox: tuple[float, float, float, float]) -> Sequence[str]: ...
    def capacity_estimate(self, edge_id: str) -> float: ...
    def get_tls(self, tls_id: str) -> Mapping[str, Any]: ...
